### ISSUE TITLE
Event handling change proposal

### ISSUE THREAD

**Issue by Trigary** [stefvanschie/QuickSkript#10]
The handling of Bukkit events is simple: you either call Skript event(s) or you don't. In case of some Bukkit events, this is even simpler: if the event fires and there is a registered Skript event, it will always get called.

Registering these kinds of simple events has been made simpler in a [recent commit of mine](https://github.com/Trigary/QuickSkript/commit/f348ead3cd271b60c08513d5d042d412f82b2c81), but this could be further improved: there is no need for a proxy object, the `AbstractEvent`.

In case of simple events, Bukkit event classes can be mapped to a collection `SkriptEvent` instances. A single event listener can execute all `SkriptEvent` instances. In case of non-simple events, the Bukkit event classes could be mapped to a collection of `SkiptEvent`, `Predicate<? extends Event>` pairs. The `SkriptEvent`s would only get executed if their `Predicate` pairs return `true`.

This would get rid of the `AbstractEvent` class, make registering events simpler, improve performance by a non-benchmarkable amount all without (hopefully) losing any features.

PS: In case I get a green light, I will gladly get this done. I would just rather get a yes/no answer before spending time with this.

**Comment by stefvanschie** [comment]
I like this idea, however keep in mind that some skript events would need to be mapped multiple times. Take for example the 'on click' event (http://skriptlang.github.io/Skript/events.html#click) which links to the `PlayerInteractEvent`. If you type 'on click', no predicate would be needed since it would trigger for all `PlayerInteractEvent`s. However you can also do 'on rightclick' in which the event only gets triggered whenever a `PlayerInteractEvent` occurs and the action is either `RIGHT_CLICK_AIR` or `RIGHT_CLICK_BLOCK`. You can also do 'on leftclick' and there are additional options for specifiying with which item needs to be clicked and on which block/entity needs to be clicked (although the ones for entities would probably be mapped to `PlayerInteractEntityEvent`).

As long as it'll be possible to register multiple different types of texts for the same event with different predicates, then I'll gladly accept the proposed changes.

**Comment by Trigary** [comment]
Great! It will fit the requirements you described.

**Comment by stefvanschie** [comment]
Closed, since this has been implemented.
