### ISSUE TITLE
TextMessage changes

### ISSUE THREAD

**Issue by Trigary** [stefvanschie/QuickSkript#19]
Issues with its current state:
 - It is essentially a wrapper around `String`: it can do nothing which wasn't possible if it were to store a `String` instance in O(N) time, but it has a higher memory requirement.
 - It is mutable, but also a simple data type (see `PsiStringLiteral`). This could cause some issues if we are not careful enough.
 - The naming doesn't always fit its function: for example, the `PsiWorldFunction` class uses this class to store the name of a `World` - something that is not a message.

Proposed changes:
 - Make it a class which just stores a `String` instance and rename it to `PsiString`. An alternative is to have it as a utility class and use `String` instances instead.
 - Make it immutable, create an `#add(String)` method which returns a new class instance.
 - Make the parsers, getters able to convert alternative color code chars into real color codes and vice versa.
 - Use `String` functions instead of regex to make the methods have a time complexity of O(N). Can use the static methods of the `ChatColor` enum whenever possible.

**Comment by stefvanschie** [comment]
The main reason I introduced a TextMessage class composed of these component-like parts is to provide a way to divide the string up in parts which can be individually altered on execution. Take for example, an instruction like this:

    message "You said %argument%"

The %argument%, which will get replaced by the argument specified in the command, can be a component and can be parsed on load time, so we only have to fill in the actual value when the command is executed. Such functionality is not yet implemented (mainly due to the lack of arguments and other replaceable types currently implemented), however would need to be implemented sometime in the future.

By parsing this special argument on load time and separating it from the rest of the string, we don't have to walk through the string when executing to find such special values which are possibly inside the string, but instead can just be replaced by the actual value directly (by simply finding all such components and filling in their actual value). This should increase execution time, since the amount of components should be less than the amount of characters inside the string (which in turn means that we have to loop through less elements).

I do agree however that the TextMessage should be immutable and that the naming is confusing for scenarios such as the one you mentioned. Renaming the class and making it immutable should definitely be done.

**Comment by Trigary** [comment]
Ah, the system makes sense now. I would still recommend against separating the colors and the text pieces though.

**Comment by stefvanschie** [comment]
I checked the skript docs and couldn't find any expression which alters chat colors in any way (apart from one that removes colors, but that can be done by ChatColor.stripColors), so merging the normal text and colors together is definitely a good idea.

**Comment by stefvanschie** [comment]
I implemented the suggested changes; renamed TextMessage, made it immutable and merged TextString and TextFormat.
