### ISSUE TITLE
Improved QuickSkript version acquisition

### ISSUE THREAD

**Issue by Trigary** [stefvanschie/QuickSkript#43]
`PsiSkriptVersionExpression` currently calls `getClass().getResourceAsStream("/app.properties")` in its constructor to acquire the QuickSkript version. I see two slight issues with this:
 - It is done in the constructor, therefore executed once for each element instance, while it really only needs to be executed once. It is not a huge issue, since this is definitely not "hot" code, but still suboptimal and triggers me. It could be done in a static block instead, or even better, it could be exposed through a getter in some central class that the `core` module has.
 - The `app.properties` file can be found in the `core` module. This module is designed to be shaded into some other jar. What if that other jar actually must use this generic file `/app.properties` for some reason, eg. a framework? I suggest placing the file in a directory or renaming it, but I would rather research how these situations are usually handled first.

**Comment by stefvanschie** [comment]
I understand why you'd want to do the retrieval of the version in a static block, but don't quite see why it'd be advantageous to expose this in a central class, since there's currently nothing else that uses this version?
I've looked up how other projects handle the file placement, but I couldn't find any kind of pattern, so I'll probably just put it in a directory and call it a day.

**Comment by Trigary** [comment]
> [...] since there's currently nothing else that uses this version?

It might have to be included in some error logs in the future.

**Comment by stefvanschie** [comment]
This has been addressed in commit eb0e22c.
